In [1]:
import numpy as np

In [2]:
num = np.arange(16, dtype='int').reshape(-1, 4)

In [3]:
print(num)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
new_num = num[::-1]

In [20]:
print(new_num)

[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
