In [1]:
import numpy as np

In [2]:
import os

In [3]:
x = np.arange(12).reshape(4, 3)

In [4]:
print(x)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
header= 'col1 col2 col3'

In [7]:
np.savetxt('temp.txt', x, fmt="%d", header=header)

In [8]:
print("after load")

after load


In [9]:
res=np.loadtxt('temp.txt')

In [10]:
print(res)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
